PREFIX foaf: <http://localhost/ontologia_medicamentos.xml#>
PREFIX owl:<http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT * 
 FROM <c:/users/federico/desktop/ontologia_medicamentos.xml>
WHERE 
{
  ?medicamento a foaf:Medicamento;
    foaf:hasVidaMedia ?vidaMedia;
    foaf:MedicamentoPrincipiosActivos ?PrincipioActivo;
    foaf:hasNombre ?Nombre;
    foaf:hasContenido ?Contenido;
    foaf:hasLaboratorio ?Laboratorio;
    foaf:hasFechaCaducidad ?Caducidad;
    FILTER (?vidaMedia < 50)
}