PREFIX : <http://inf.ed.ac.uk/ont#> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
FROM <http://www.inf.ed.ac.uk/teaching/courses/masws/coding/build/html/_downloads/knows.n3>
FROM <http://www.inf.ed.ac.uk/teaching/courses/masws/coding/build/html/_downloads/cafes.n3>
SELECT ?cafe ?x 
WHERE 
    {
      ?cafe :lovedBy ?x .
      {
       ?x foaf:knows ?y .
      }
      UNION
      {
       ?y foaf:knows ?x .
      }
    } 