PREFIX foaf: <http://localhost/ontologia_medicamentos.xml#>
PREFIX owl:<http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?medicamento ?excipiente
FROM <http://localhost/ontologia_medicamentos.xml> 
WHERE 
{
   	{
		?excipiente rdf:type foaf:Excipiente; 
		foaf:hasExcipienteFuncion foaf:Lubricante
   	} 
	UNION 
	{
		?excipiente foaf:hasExcipienteFuncion foaf:Colorante
   	}
   
   FILTER (?medicamento = <http://localhost/ontologia_medicamentos.xml#Moxtam>)
   ?medicamento foaf:MedicamentoExcipientes ?excipiente

}